// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt_bB7-mpCqFuyuQ654_2TcCSe_3j7j_I',
    appId: '1:631027762737:web:4144ec937d01fb9bcc7710',
    messagingSenderId: '631027762737',
    projectId: 'attendance-app-ttl',
    authDomain: 'attendance-app-ttl.firebaseapp.com',
    storageBucket: 'attendance-app-ttl.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQUIWpOo6s0D6TrX-0bo-4BNl_2XoqB4U',
    appId: '1:631027762737:android:d2e282c6deac50cecc7710',
    messagingSenderId: '631027762737',
    projectId: 'attendance-app-ttl',
    storageBucket: 'attendance-app-ttl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG_oifREj6EvHPt5rg8W-8D27uShbQ33g',
    appId: '1:631027762737:ios:ad0ed8414f2baf9fcc7710',
    messagingSenderId: '631027762737',
    projectId: 'attendance-app-ttl',
    storageBucket: 'attendance-app-ttl.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );
}
